version: "3.7"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rentx
    ports:
      - 5555:5432
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local