version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rentx
    ports:
      - 5555:5432
    volumes: 
      - db:/var/lib/postgresql/data
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
volumes:
  db:
    driver: local