version: "3.7"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      -  POSTGRES_DB=rentx
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  db:
    driver: local